#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_Thu_Vien")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdausach(dausach instance);
    partial void Updatedausach(dausach instance);
    partial void Deletedausach(dausach instance);
    partial void Inserthoadon_thue(hoadon_thue instance);
    partial void Updatehoadon_thue(hoadon_thue instance);
    partial void Deletehoadon_thue(hoadon_thue instance);
    partial void Inserthoadon_tra(hoadon_tra instance);
    partial void Updatehoadon_tra(hoadon_tra instance);
    partial void Deletehoadon_tra(hoadon_tra instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertnguoidung(nguoidung instance);
    partial void Updatenguoidung(nguoidung instance);
    partial void Deletenguoidung(nguoidung instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertsach(sach instance);
    partial void Updatesach(sach instance);
    partial void Deletesach(sach instance);
    partial void InsertvaiTro(vaiTro instance);
    partial void UpdatevaiTro(vaiTro instance);
    partial void DeletevaiTro(vaiTro instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QLTV.Properties.Settings.Default.QL_Thu_VienConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dausach> dausaches
		{
			get
			{
				return this.GetTable<dausach>();
			}
		}
		
		public System.Data.Linq.Table<hoadon_thue> hoadon_thues
		{
			get
			{
				return this.GetTable<hoadon_thue>();
			}
		}
		
		public System.Data.Linq.Table<hoadon_tra> hoadon_tras
		{
			get
			{
				return this.GetTable<hoadon_tra>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<nguoidung> nguoidungs
		{
			get
			{
				return this.GetTable<nguoidung>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<sach> saches
		{
			get
			{
				return this.GetTable<sach>();
			}
		}
		
		public System.Data.Linq.Table<vaiTro> vaiTros
		{
			get
			{
				return this.GetTable<vaiTro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dausach")]
	public partial class dausach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_dausach;
		
		private string _ten_dausach;
		
		private System.Nullable<int> _so_luong;
		
		private string _ten_tacgia;
		
		private string _theloai;
		
		private System.Nullable<int> _soluongconlai;
		
		private EntitySet<hoadon_thue> _hoadon_thues;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_dausachChanging(int value);
    partial void Onma_dausachChanged();
    partial void Onten_dausachChanging(string value);
    partial void Onten_dausachChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void Onten_tacgiaChanging(string value);
    partial void Onten_tacgiaChanged();
    partial void OntheloaiChanging(string value);
    partial void OntheloaiChanged();
    partial void OnsoluongconlaiChanging(System.Nullable<int> value);
    partial void OnsoluongconlaiChanged();
    #endregion
		
		public dausach()
		{
			this._hoadon_thues = new EntitySet<hoadon_thue>(new Action<hoadon_thue>(this.attach_hoadon_thues), new Action<hoadon_thue>(this.detach_hoadon_thues));
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_dausach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_dausach
		{
			get
			{
				return this._ma_dausach;
			}
			set
			{
				if ((this._ma_dausach != value))
				{
					this.Onma_dausachChanging(value);
					this.SendPropertyChanging();
					this._ma_dausach = value;
					this.SendPropertyChanged("ma_dausach");
					this.Onma_dausachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dausach", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_dausach
		{
			get
			{
				return this._ten_dausach;
			}
			set
			{
				if ((this._ten_dausach != value))
				{
					this.Onten_dausachChanging(value);
					this.SendPropertyChanging();
					this._ten_dausach = value;
					this.SendPropertyChanged("ten_dausach");
					this.Onten_dausachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_tacgia", DbType="NVarChar(255)")]
		public string ten_tacgia
		{
			get
			{
				return this._ten_tacgia;
			}
			set
			{
				if ((this._ten_tacgia != value))
				{
					this.Onten_tacgiaChanging(value);
					this.SendPropertyChanging();
					this._ten_tacgia = value;
					this.SendPropertyChanged("ten_tacgia");
					this.Onten_tacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theloai", DbType="NVarChar(255)")]
		public string theloai
		{
			get
			{
				return this._theloai;
			}
			set
			{
				if ((this._theloai != value))
				{
					this.OntheloaiChanging(value);
					this.SendPropertyChanging();
					this._theloai = value;
					this.SendPropertyChanged("theloai");
					this.OntheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongconlai", DbType="Int")]
		public System.Nullable<int> soluongconlai
		{
			get
			{
				return this._soluongconlai;
			}
			set
			{
				if ((this._soluongconlai != value))
				{
					this.OnsoluongconlaiChanging(value);
					this.SendPropertyChanging();
					this._soluongconlai = value;
					this.SendPropertyChanged("soluongconlai");
					this.OnsoluongconlaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dausach_hoadon_thue", Storage="_hoadon_thues", ThisKey="ma_dausach", OtherKey="id_dausach")]
		public EntitySet<hoadon_thue> hoadon_thues
		{
			get
			{
				return this._hoadon_thues;
			}
			set
			{
				this._hoadon_thues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dausach_sach", Storage="_saches", ThisKey="ma_dausach", OtherKey="id_dausach")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadon_thues(hoadon_thue entity)
		{
			this.SendPropertyChanging();
			entity.dausach = this;
		}
		
		private void detach_hoadon_thues(hoadon_thue entity)
		{
			this.SendPropertyChanging();
			entity.dausach = null;
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.dausach = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.dausach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon_thue")]
	public partial class hoadon_thue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hoadon_thue;
		
		private System.Nullable<System.DateTime> _ngay_thue;
		
		private System.Nullable<int> _id_dausach;
		
		private System.Nullable<int> _id_khachhang;
		
		private System.Nullable<double> _gia_thue;
		
		private System.Nullable<double> _tien_coc;
		
		private EntitySet<hoadon_tra> _hoadon_tras;
		
		private EntityRef<dausach> _dausach;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoadon_thueChanging(int value);
    partial void Onid_hoadon_thueChanged();
    partial void Onngay_thueChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_thueChanged();
    partial void Onid_dausachChanging(System.Nullable<int> value);
    partial void Onid_dausachChanged();
    partial void Onid_khachhangChanging(System.Nullable<int> value);
    partial void Onid_khachhangChanged();
    partial void Ongia_thueChanging(System.Nullable<double> value);
    partial void Ongia_thueChanged();
    partial void Ontien_cocChanging(System.Nullable<double> value);
    partial void Ontien_cocChanged();
    #endregion
		
		public hoadon_thue()
		{
			this._hoadon_tras = new EntitySet<hoadon_tra>(new Action<hoadon_tra>(this.attach_hoadon_tras), new Action<hoadon_tra>(this.detach_hoadon_tras));
			this._dausach = default(EntityRef<dausach>);
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoadon_thue", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_hoadon_thue
		{
			get
			{
				return this._id_hoadon_thue;
			}
			set
			{
				if ((this._id_hoadon_thue != value))
				{
					this.Onid_hoadon_thueChanging(value);
					this.SendPropertyChanging();
					this._id_hoadon_thue = value;
					this.SendPropertyChanged("id_hoadon_thue");
					this.Onid_hoadon_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_thue", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_thue
		{
			get
			{
				return this._ngay_thue;
			}
			set
			{
				if ((this._ngay_thue != value))
				{
					this.Onngay_thueChanging(value);
					this.SendPropertyChanging();
					this._ngay_thue = value;
					this.SendPropertyChanged("ngay_thue");
					this.Onngay_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dausach", DbType="Int")]
		public System.Nullable<int> id_dausach
		{
			get
			{
				return this._id_dausach;
			}
			set
			{
				if ((this._id_dausach != value))
				{
					if (this._dausach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dausachChanging(value);
					this.SendPropertyChanging();
					this._id_dausach = value;
					this.SendPropertyChanged("id_dausach");
					this.Onid_dausachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khachhang", DbType="Int")]
		public System.Nullable<int> id_khachhang
		{
			get
			{
				return this._id_khachhang;
			}
			set
			{
				if ((this._id_khachhang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khachhangChanging(value);
					this.SendPropertyChanging();
					this._id_khachhang = value;
					this.SendPropertyChanged("id_khachhang");
					this.Onid_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_thue", DbType="Float")]
		public System.Nullable<double> gia_thue
		{
			get
			{
				return this._gia_thue;
			}
			set
			{
				if ((this._gia_thue != value))
				{
					this.Ongia_thueChanging(value);
					this.SendPropertyChanging();
					this._gia_thue = value;
					this.SendPropertyChanged("gia_thue");
					this.Ongia_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tien_coc", DbType="Float")]
		public System.Nullable<double> tien_coc
		{
			get
			{
				return this._tien_coc;
			}
			set
			{
				if ((this._tien_coc != value))
				{
					this.Ontien_cocChanging(value);
					this.SendPropertyChanging();
					this._tien_coc = value;
					this.SendPropertyChanged("tien_coc");
					this.Ontien_cocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_thue_hoadon_tra", Storage="_hoadon_tras", ThisKey="id_hoadon_thue", OtherKey="id_hoadon_thue")]
		public EntitySet<hoadon_tra> hoadon_tras
		{
			get
			{
				return this._hoadon_tras;
			}
			set
			{
				this._hoadon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dausach_hoadon_thue", Storage="_dausach", ThisKey="id_dausach", OtherKey="ma_dausach", IsForeignKey=true)]
		public dausach dausach
		{
			get
			{
				return this._dausach.Entity;
			}
			set
			{
				dausach previousValue = this._dausach.Entity;
				if (((previousValue != value) 
							|| (this._dausach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dausach.Entity = null;
						previousValue.hoadon_thues.Remove(this);
					}
					this._dausach.Entity = value;
					if ((value != null))
					{
						value.hoadon_thues.Add(this);
						this._id_dausach = value.ma_dausach;
					}
					else
					{
						this._id_dausach = default(Nullable<int>);
					}
					this.SendPropertyChanged("dausach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon_thue", Storage="_khachhang", ThisKey="id_khachhang", OtherKey="ma_khachhang", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.hoadon_thues.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.hoadon_thues.Add(this);
						this._id_khachhang = value.ma_khachhang;
					}
					else
					{
						this._id_khachhang = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadon_tras(hoadon_tra entity)
		{
			this.SendPropertyChanging();
			entity.hoadon_thue = this;
		}
		
		private void detach_hoadon_tras(hoadon_tra entity)
		{
			this.SendPropertyChanging();
			entity.hoadon_thue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon_tra")]
	public partial class hoadon_tra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hoadon_tra;
		
		private System.Nullable<System.DateTime> _ngay_tra;
		
		private System.Nullable<int> _id_hoadon_thue;
		
		private EntityRef<hoadon_thue> _hoadon_thue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoadon_traChanging(int value);
    partial void Onid_hoadon_traChanged();
    partial void Onngay_traChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_traChanged();
    partial void Onid_hoadon_thueChanging(System.Nullable<int> value);
    partial void Onid_hoadon_thueChanged();
    #endregion
		
		public hoadon_tra()
		{
			this._hoadon_thue = default(EntityRef<hoadon_thue>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoadon_tra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_hoadon_tra
		{
			get
			{
				return this._id_hoadon_tra;
			}
			set
			{
				if ((this._id_hoadon_tra != value))
				{
					this.Onid_hoadon_traChanging(value);
					this.SendPropertyChanging();
					this._id_hoadon_tra = value;
					this.SendPropertyChanged("id_hoadon_tra");
					this.Onid_hoadon_traChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tra", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_tra
		{
			get
			{
				return this._ngay_tra;
			}
			set
			{
				if ((this._ngay_tra != value))
				{
					this.Onngay_traChanging(value);
					this.SendPropertyChanging();
					this._ngay_tra = value;
					this.SendPropertyChanged("ngay_tra");
					this.Onngay_traChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoadon_thue", DbType="Int")]
		public System.Nullable<int> id_hoadon_thue
		{
			get
			{
				return this._id_hoadon_thue;
			}
			set
			{
				if ((this._id_hoadon_thue != value))
				{
					if (this._hoadon_thue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hoadon_thueChanging(value);
					this.SendPropertyChanging();
					this._id_hoadon_thue = value;
					this.SendPropertyChanged("id_hoadon_thue");
					this.Onid_hoadon_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_thue_hoadon_tra", Storage="_hoadon_thue", ThisKey="id_hoadon_thue", OtherKey="id_hoadon_thue", IsForeignKey=true)]
		public hoadon_thue hoadon_thue
		{
			get
			{
				return this._hoadon_thue.Entity;
			}
			set
			{
				hoadon_thue previousValue = this._hoadon_thue.Entity;
				if (((previousValue != value) 
							|| (this._hoadon_thue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoadon_thue.Entity = null;
						previousValue.hoadon_tras.Remove(this);
					}
					this._hoadon_thue.Entity = value;
					if ((value != null))
					{
						value.hoadon_tras.Add(this);
						this._id_hoadon_thue = value.id_hoadon_thue;
					}
					else
					{
						this._id_hoadon_thue = default(Nullable<int>);
					}
					this.SendPropertyChanged("hoadon_thue");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_khachhang;
		
		private string _ten_khachhang;
		
		private string _so_dienthoai;
		
		private EntitySet<hoadon_thue> _hoadon_thues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_khachhangChanging(int value);
    partial void Onma_khachhangChanged();
    partial void Onten_khachhangChanging(string value);
    partial void Onten_khachhangChanged();
    partial void Onso_dienthoaiChanging(string value);
    partial void Onso_dienthoaiChanged();
    #endregion
		
		public khachhang()
		{
			this._hoadon_thues = new EntitySet<hoadon_thue>(new Action<hoadon_thue>(this.attach_hoadon_thues), new Action<hoadon_thue>(this.detach_hoadon_thues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_khachhang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_khachhang
		{
			get
			{
				return this._ma_khachhang;
			}
			set
			{
				if ((this._ma_khachhang != value))
				{
					this.Onma_khachhangChanging(value);
					this.SendPropertyChanging();
					this._ma_khachhang = value;
					this.SendPropertyChanged("ma_khachhang");
					this.Onma_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khachhang", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_khachhang
		{
			get
			{
				return this._ten_khachhang;
			}
			set
			{
				if ((this._ten_khachhang != value))
				{
					this.Onten_khachhangChanging(value);
					this.SendPropertyChanging();
					this._ten_khachhang = value;
					this.SendPropertyChanged("ten_khachhang");
					this.Onten_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dienthoai", DbType="NVarChar(20)")]
		public string so_dienthoai
		{
			get
			{
				return this._so_dienthoai;
			}
			set
			{
				if ((this._so_dienthoai != value))
				{
					this.Onso_dienthoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dienthoai = value;
					this.SendPropertyChanged("so_dienthoai");
					this.Onso_dienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon_thue", Storage="_hoadon_thues", ThisKey="ma_khachhang", OtherKey="id_khachhang")]
		public EntitySet<hoadon_thue> hoadon_thues
		{
			get
			{
				return this._hoadon_thues;
			}
			set
			{
				this._hoadon_thues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadon_thues(hoadon_thue entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_hoadon_thues(hoadon_thue entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nguoidung")]
	public partial class nguoidung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nguoidung;
		
		private string _tendangnhap;
		
		private string _matkhau;
		
		private EntitySet<vaiTro> _vaiTros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nguoidungChanging(int value);
    partial void Onid_nguoidungChanged();
    partial void OntendangnhapChanging(string value);
    partial void OntendangnhapChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public nguoidung()
		{
			this._vaiTros = new EntitySet<vaiTro>(new Action<vaiTro>(this.attach_vaiTros), new Action<vaiTro>(this.detach_vaiTros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nguoidung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nguoidung
		{
			get
			{
				return this._id_nguoidung;
			}
			set
			{
				if ((this._id_nguoidung != value))
				{
					this.Onid_nguoidungChanging(value);
					this.SendPropertyChanging();
					this._id_nguoidung = value;
					this.SendPropertyChanged("id_nguoidung");
					this.Onid_nguoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendangnhap", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string tendangnhap
		{
			get
			{
				return this._tendangnhap;
			}
			set
			{
				if ((this._tendangnhap != value))
				{
					this.OntendangnhapChanging(value);
					this.SendPropertyChanging();
					this._tendangnhap = value;
					this.SendPropertyChanged("tendangnhap");
					this.OntendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoidung_vaiTro", Storage="_vaiTros", ThisKey="id_nguoidung", OtherKey="id_nguoidung")]
		public EntitySet<vaiTro> vaiTros
		{
			get
			{
				return this._vaiTros;
			}
			set
			{
				this._vaiTros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_vaiTros(vaiTro entity)
		{
			this.SendPropertyChanging();
			entity.nguoidung = this;
		}
		
		private void detach_vaiTros(vaiTro entity)
		{
			this.SendPropertyChanging();
			entity.nguoidung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_nhanvien;
		
		private string _ten_nhanvien;
		
		private string _so_dienthoai;
		
		private string _dia_chi;
		
		private string _gioitinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_nhanvienChanging(int value);
    partial void Onma_nhanvienChanged();
    partial void Onten_nhanvienChanging(string value);
    partial void Onten_nhanvienChanged();
    partial void Onso_dienthoaiChanging(string value);
    partial void Onso_dienthoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    #endregion
		
		public nhanvien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhanvien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_nhanvien
		{
			get
			{
				return this._ma_nhanvien;
			}
			set
			{
				if ((this._ma_nhanvien != value))
				{
					this.Onma_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._ma_nhanvien = value;
					this.SendPropertyChanged("ma_nhanvien");
					this.Onma_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nhanvien", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_nhanvien
		{
			get
			{
				return this._ten_nhanvien;
			}
			set
			{
				if ((this._ten_nhanvien != value))
				{
					this.Onten_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._ten_nhanvien = value;
					this.SendPropertyChanged("ten_nhanvien");
					this.Onten_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dienthoai", DbType="NVarChar(20)")]
		public string so_dienthoai
		{
			get
			{
				return this._so_dienthoai;
			}
			set
			{
				if ((this._so_dienthoai != value))
				{
					this.Onso_dienthoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dienthoai = value;
					this.SendPropertyChanged("so_dienthoai");
					this.Onso_dienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(255)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sach")]
	public partial class sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sach;
		
		private System.Nullable<bool> _Trangthai;
		
		private System.Nullable<int> _id_dausach;
		
		private EntityRef<dausach> _dausach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sachChanging(int value);
    partial void Onid_sachChanged();
    partial void OnTrangthaiChanging(System.Nullable<bool> value);
    partial void OnTrangthaiChanged();
    partial void Onid_dausachChanging(System.Nullable<int> value);
    partial void Onid_dausachChanged();
    #endregion
		
		public sach()
		{
			this._dausach = default(EntityRef<dausach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sach
		{
			get
			{
				return this._id_sach;
			}
			set
			{
				if ((this._id_sach != value))
				{
					this.Onid_sachChanging(value);
					this.SendPropertyChanging();
					this._id_sach = value;
					this.SendPropertyChanged("id_sach");
					this.Onid_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Bit")]
		public System.Nullable<bool> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dausach", DbType="Int")]
		public System.Nullable<int> id_dausach
		{
			get
			{
				return this._id_dausach;
			}
			set
			{
				if ((this._id_dausach != value))
				{
					if (this._dausach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dausachChanging(value);
					this.SendPropertyChanging();
					this._id_dausach = value;
					this.SendPropertyChanged("id_dausach");
					this.Onid_dausachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dausach_sach", Storage="_dausach", ThisKey="id_dausach", OtherKey="ma_dausach", IsForeignKey=true)]
		public dausach dausach
		{
			get
			{
				return this._dausach.Entity;
			}
			set
			{
				dausach previousValue = this._dausach.Entity;
				if (((previousValue != value) 
							|| (this._dausach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dausach.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._dausach.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._id_dausach = value.ma_dausach;
					}
					else
					{
						this._id_dausach = default(Nullable<int>);
					}
					this.SendPropertyChanged("dausach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vaiTro")]
	public partial class vaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vaitro;
		
		private string _tenVaiTro;
		
		private System.Nullable<int> _id_nguoidung;
		
		private EntityRef<nguoidung> _nguoidung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vaitroChanging(int value);
    partial void Onid_vaitroChanged();
    partial void OntenVaiTroChanging(string value);
    partial void OntenVaiTroChanged();
    partial void Onid_nguoidungChanging(System.Nullable<int> value);
    partial void Onid_nguoidungChanged();
    #endregion
		
		public vaiTro()
		{
			this._nguoidung = default(EntityRef<nguoidung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vaitro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_vaitro
		{
			get
			{
				return this._id_vaitro;
			}
			set
			{
				if ((this._id_vaitro != value))
				{
					this.Onid_vaitroChanging(value);
					this.SendPropertyChanging();
					this._id_vaitro = value;
					this.SendPropertyChanged("id_vaitro");
					this.Onid_vaitroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenVaiTro", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string tenVaiTro
		{
			get
			{
				return this._tenVaiTro;
			}
			set
			{
				if ((this._tenVaiTro != value))
				{
					this.OntenVaiTroChanging(value);
					this.SendPropertyChanging();
					this._tenVaiTro = value;
					this.SendPropertyChanged("tenVaiTro");
					this.OntenVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nguoidung", DbType="Int")]
		public System.Nullable<int> id_nguoidung
		{
			get
			{
				return this._id_nguoidung;
			}
			set
			{
				if ((this._id_nguoidung != value))
				{
					if (this._nguoidung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nguoidungChanging(value);
					this.SendPropertyChanging();
					this._id_nguoidung = value;
					this.SendPropertyChanged("id_nguoidung");
					this.Onid_nguoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoidung_vaiTro", Storage="_nguoidung", ThisKey="id_nguoidung", OtherKey="id_nguoidung", IsForeignKey=true)]
		public nguoidung nguoidung
		{
			get
			{
				return this._nguoidung.Entity;
			}
			set
			{
				nguoidung previousValue = this._nguoidung.Entity;
				if (((previousValue != value) 
							|| (this._nguoidung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nguoidung.Entity = null;
						previousValue.vaiTros.Remove(this);
					}
					this._nguoidung.Entity = value;
					if ((value != null))
					{
						value.vaiTros.Add(this);
						this._id_nguoidung = value.id_nguoidung;
					}
					else
					{
						this._id_nguoidung = default(Nullable<int>);
					}
					this.SendPropertyChanged("nguoidung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
